### PR TITLE
Change display name to Runtime Connector

### PR DESCRIPTION
**Pull request by aidenkeating**
@finp @johnfriz @sedroche @wei-lee  Based on changes suggested by @finp. Mind taking a look?

### CODE REVIEW

**Review by sedroche — APPROVED** [review]

**Comment by johnfriz** [comment]
Hmmmmm.... The output from the [job](https://jenkins-wendy.ci.feedhenry.org/blue/organizations/jenkins/AeroGearCatalog%2Fcustom-runtime-connector-apb/detail/PR-22/1/pipeline) says that `docker logs" requires exactly 1 argument(s).`

the command being run is `docker logs -f`

Seems like the container Id is not being passed as per the docs: https://docs.docker.com/engine/reference/commandline/logs/

Is this of concern?

cc @wei-lee

**Comment by wei-lee** [comment]
Retest this please

**Comment by wei-lee** [comment]
@aidenkeating @johnfriz The container id should be set from this step: https://github.com/aerogearcatalog/custom-runtime-connector-apb/blob/master/Jenkinsfile#L30. But looks like it is empty.

I don't think it is related to this change, as by looking at the build history there are builds failed with the same reason, looks like it could be a timing issue. I think we should try rebuild and see if it will work. Although not sure how to trigger a rebuild. @grdryn any idea?

**Comment by grdryn** [comment]
@wei-lee To trigger a rebuild, you just need to follow the 'Details' link to the Jenkins job in the status check, login there, and hit the rebuild button. I've triggered a rebuild now for you, but it has failed again.

@psturc any idea why this is failing? I did a replay and stuck in a couple of echo steps:

https://jenkins-wendy.ci.feedhenry.org/job/AeroGearCatalog/job/custom-runtime-connector-apb/job/PR-22/3/console

```
apb_container_id: 7d690ab13ce5b07ef142581c5f8ca342eb2925a11db360531f416c1f00a3d11a
pod_container_id: 
```

**Comment by wei-lee** [comment]
@grdryn thanks for the instructions. But I keep getting authentication errors when I tried to login via Openshift. Any idea why?

**Comment by grdryn** [comment]
@wei-lee Hmm, is it just when you try to login to Jenkins via OpenShift? Are you able to login to OpenShift itself with your GitHub account, here https://ci.feedhenry.org:8443 ?

**Comment by wei-lee** [comment]
@grdryn never mind. looks like it is a problem with a previous login session. It is working now after I cleared the site data for that openshift instance. Thanks for the help!

**Comment by pawelpaszki** [comment]
The name has been changed as expected:

services

**Pull request merged**
