### PR TITLE
Add tests for provision/deprovision

### PR DESCRIPTION
**Pull request by ghost**
**VERIFICATION**
`apb test`

**Result:**
...
Pod phase Succeeded without returning test results
Unable to retrieve test result.
Deleting project apb-test-custom-runtime-connector-apb-jbeew
Project deleted

### CODE REVIEW

**Review by maleck13 — COMMENTED** [review]
I think Adam or Pavel may be better suited to review this @psturc

**Comment by psturc** [comment]
@vchepeli I have currently no idea why it's failing in CI. Will try this locally

**Comment by psturc** [comment]
I verified this locally, but CI is failing with some weird error.
We could try to change the approach to the CI test basically by running `apb test` on the new OCP slave. I will update the PR with changes to Jenkinsfile

**Comment by psturc** [comment]
@vchepeli  CI test is working. If you're happy with it, we can merge this PR

**Review by psturc — APPROVED** [review]

**Pull request merged**
